# Generated by Django 4.1.4 on 2023-01-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="date",
        ),
    ]
