# Generated by Django 4.1.4 on 2022-12-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="titles",
            new_name="title",
        ),
    ]
